script:
      # Check that examples compile
    - sed -n '/``` cpp/,${/```$/q;/```/d;p}' README.md > main.cpp &&
      PYTHONPATH=mbed-os python mbed-os/tools/make.py -t GCC_ARM -m K82F
          --source=. --build=BUILD/K82F/GCC_ARM -j0 &&
      rm main.cpp
    - sed -n '/@code/,${/@endcode/q;/@/d;s/^ \*//;p}' SPIFBlockDevice.h > main.cpp &&
      PYTHONPATH=mbed-os python mbed-os/tools/make.py -t GCC_ARM -m K82F
          --source=. --build=BUILD/K82F/GCC_ARM -j0 &&
      rm main.cpp

      # Check that tests compile
    - rm -r BUILD && PYTHONPATH=mbed-os python mbed-os/tools/test.py
          -t GCC_ARM -m K82F --source=. --build=BUILD/TESTS/K82F/GCC_ARM -j0
          -n tests*

cache:
  pip: true
  directories:
    - $HOME/.cache/apt

before_install:
    # Make sure pipefail
    - set -o pipefail
    # Setup apt to cache
    - mkdir -p $HOME/.cache/apt/partial
    - sudo rm -rf /var/cache/apt/archives
    - sudo ln -s $HOME/.cache/apt /var/cache/apt/archives
    # Setup ppa to make sure arm-none-eabi-gcc is correct version
    - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
    - sudo apt-get update -qq

install:
    # Get arm-none-eabi-gcc
    - sudo apt-get install -qq gcc-arm-embedded --force-yes
    # Get dependencies
    - git clone https://github.com/armmbed/mbed-os.git
    # Install python dependencies
    - sudo pip install -r mbed-os/requirements.txt

deploy:
    # Let before_deploy take over
    provider: script
    script: 'true'
    on:
        branch: versioning

before_deploy:
    # Update tag for version
    - SPIF_DRIVER_VERSION=$(
        grep -ox '#define SPIF_DRIVER_VERSION .*' SPIFBlockDevice.h
            | cut -d ' ' -f3)
    - SPIF_DRIVER_VERSION_MAJOR=$((0xffff & ($SPIF_DRIVER_VERSION >> 16)))
    - SPIF_DRIVER_VERSION_MINOR=$((0xffff & ($SPIF_DRIVER_VERSION >>  0)))
    - SPIF_DRIVER_VERSION="v$SPIF_DRIVER_VERSION_MAJOR.$SPIF_DRIVER_VERSION_MINOR"
    - |
      curl -u $MBED_BOT -X POST \
        https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs \
        -d "{
          \"ref\": \"refs/tags/$SPIF_DRIVER_VERSION\",
          \"sha\": \"$TRAVIS_COMMIT\"
        }"
    - |
      curl -f -u $MBED_BOT -X PATCH \
        https://api.github.com/repos/$TRAVIS_REPO_SLUG/git/refs/tags/$SPIF_DRIVER_VERSION \
        -d "{
          \"sha\": \"$TRAVIS_COMMIT\"
        }"
    # Create release notes from commits
    - SPIF_DRIVER_PREV_VERSION="v$SPIF_DRIVER_VERSION_MAJOR.$(($SPIF_DRIVER_VERSION_MINOR-1))"
    - |
      if [ $(git tag -l "$SPIF_DRIVER_PREV_VERSION") ]
      then
        curl -u $MBED_BOT -X POST \
            https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases \
            -d "{
                \"tag_name\": \"$SPIF_DRIVER_VERSION\"
            }"
        curl -f -u $MBED_BOT -X PATCH \
            https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases/$( \
                curl -f https://api.github.com/repos/$TRAVIS_REPO_SLUG/releases/tags/$SPIF_DRIVER_VERSION \
                    | jq -r '.id'
            ) \
            -d "$( \
                git log --oneline $SPIF_DRIVER_PREV_VERSION.. \
                    --grep='^Merge' --invert-grep \
                    | jq -sR '{"body":.}'
            )"
      fi
